// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250414160523_litacore06")]
    partial class litacore06
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Database.Item.Item", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<short>("Id"));

                    b.Property<byte>("CellonLevel")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("cellonlevel");

                    b.Property<short>("CloseDefence")
                        .HasColumnType("smallint")
                        .HasColumnName("closedefence");

                    b.Property<byte>("Color")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("color");

                    b.Property<short>("Concentrate")
                        .HasColumnType("smallint")
                        .HasColumnName("concentrate");

                    b.Property<byte>("CriticalLuckRate")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("criticalluckrate");

                    b.Property<short>("CriticalRate")
                        .HasColumnType("smallint")
                        .HasColumnName("criticalrate");

                    b.Property<short>("DamageMaximum")
                        .HasColumnType("smallint")
                        .HasColumnName("damagemaximum");

                    b.Property<short>("DamageMinimum")
                        .HasColumnType("smallint")
                        .HasColumnName("damageminimum");

                    b.Property<byte>("DarkElement")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("darkelement");

                    b.Property<short>("DarkResistance")
                        .HasColumnType("smallint")
                        .HasColumnName("darkresistance");

                    b.Property<byte>("DefaultUpgrade")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("defaultupgrade");

                    b.Property<short>("DefenceDodge")
                        .HasColumnType("smallint")
                        .HasColumnName("defencedodge");

                    b.Property<short>("DistanceDefence")
                        .HasColumnType("smallint")
                        .HasColumnName("distancedefence");

                    b.Property<short>("DistanceDefenceDodge")
                        .HasColumnType("smallint")
                        .HasColumnName("distancedefencedodge");

                    b.Property<short>("Effect")
                        .HasColumnType("smallint")
                        .HasColumnName("effect");

                    b.Property<int>("EffectData")
                        .HasColumnType("int")
                        .HasColumnName("effectdata");

                    b.Property<byte>("Element")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("element");

                    b.Property<short>("ElementRate")
                        .HasColumnType("smallint")
                        .HasColumnName("elementrate");

                    b.Property<int>("EquipmentSlot")
                        .HasColumnType("int")
                        .HasColumnName("equipmentslot");

                    b.Property<byte>("FireElement")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("fireelement");

                    b.Property<short>("FireResistance")
                        .HasColumnType("smallint")
                        .HasColumnName("fireresistance");

                    b.Property<byte>("Height")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("height");

                    b.Property<short>("HitRate")
                        .HasColumnType("smallint")
                        .HasColumnName("hitrate");

                    b.Property<short>("Hp")
                        .HasColumnType("smallint")
                        .HasColumnName("hp");

                    b.Property<short>("HpRegeneration")
                        .HasColumnType("smallint")
                        .HasColumnName("hpregeneration");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isblocked");

                    b.Property<bool>("IsColored")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("iscolored");

                    b.Property<bool>("IsConsumable")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isconsumable");

                    b.Property<bool>("IsDroppable")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isdroppable");

                    b.Property<bool>("IsHeroic")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isheroic");

                    b.Property<bool>("IsHolder")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isholder");

                    b.Property<bool>("IsMinilandObject")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isminilandobject");

                    b.Property<bool>("IsSoldable")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("issoldable");

                    b.Property<bool>("IsTradable")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("istradable");

                    b.Property<byte>("ItemSubType")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("itemsubtype");

                    b.Property<int>("ItemType")
                        .HasColumnType("int")
                        .HasColumnName("itemtype");

                    b.Property<long>("ItemValidTime")
                        .HasColumnType("bigint")
                        .HasColumnName("itemvalidtime");

                    b.Property<byte>("LevelJobMinimum")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("leveljobminimum");

                    b.Property<byte>("LevelMinimum")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("levelminimum");

                    b.Property<byte>("LightElement")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("lightelement");

                    b.Property<short>("LightResistance")
                        .HasColumnType("smallint")
                        .HasColumnName("lightresistance");

                    b.Property<short>("MagicDefence")
                        .HasColumnType("smallint")
                        .HasColumnName("magicdefence");

                    b.Property<short>("MaxCellon")
                        .HasColumnType("smallint")
                        .HasColumnName("maxcellon");

                    b.Property<short>("MaxCellonLvl")
                        .HasColumnType("smallint")
                        .HasColumnName("maxcellonlvl");

                    b.Property<short>("MaxElementRate")
                        .HasColumnType("smallint")
                        .HasColumnName("maxelementrate");

                    b.Property<byte>("MaximumAmmo")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("maximumammo");

                    b.Property<int>("MinilandObjectPoint")
                        .HasColumnType("int")
                        .HasColumnName("minilandobjectpoint");

                    b.Property<short>("MoreHp")
                        .HasColumnType("smallint")
                        .HasColumnName("morehp");

                    b.Property<short>("MoreMp")
                        .HasColumnType("smallint")
                        .HasColumnName("moremp");

                    b.Property<short>("Morph")
                        .HasColumnType("smallint")
                        .HasColumnName("morph");

                    b.Property<short>("Mp")
                        .HasColumnType("smallint")
                        .HasColumnName("mp");

                    b.Property<short>("MpRegeneration")
                        .HasColumnType("smallint")
                        .HasColumnName("mpregeneration");

                    b.Property<long>("Price")
                        .HasColumnType("bigint")
                        .HasColumnName("price");

                    b.Property<short>("PvpDefence")
                        .HasColumnType("smallint")
                        .HasColumnName("pvpdefence");

                    b.Property<byte>("PvpStrength")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("pvpstrength");

                    b.Property<short>("ReduceOposantResistance")
                        .HasColumnType("smallint")
                        .HasColumnName("reduceoposantresistance");

                    b.Property<long>("ReputPrice")
                        .HasColumnType("bigint")
                        .HasColumnName("reputprice");

                    b.Property<byte>("ReputationMinimum")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("reputationminimum");

                    b.Property<byte>("RequiredClass")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("requiredclass");

                    b.Property<byte>("SecondaryElement")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("secondaryelement");

                    b.Property<long>("SellToNpcPrice")
                        .HasColumnType("bigint")
                        .HasColumnName("selltonpcprice");

                    b.Property<byte>("Sex")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("sex");

                    b.Property<byte>("SpType")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("sptype");

                    b.Property<byte>("Speed")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("speed");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<short>("WaitDelay")
                        .HasColumnType("smallint")
                        .HasColumnName("waitdelay");

                    b.Property<byte>("WaterElement")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("waterelement");

                    b.Property<short>("WaterResistance")
                        .HasColumnType("smallint")
                        .HasColumnName("waterresistance");

                    b.Property<byte>("Width")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("Database.Item.ItemTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("ItemId")
                        .HasColumnType("smallint")
                        .HasColumnName("itemid");

                    b.Property<int>("Language")
                        .HasColumnType("int")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("items_translations", (string)null);
                });

            modelBuilder.Entity("Database.Player.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsBanned")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isbanned");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<byte>("Rank")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("rank");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Database.Player.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("accountid");

                    b.Property<int>("Act4DeadCount")
                        .HasColumnType("int")
                        .HasColumnName("act4deadcount");

                    b.Property<int>("Act4Points")
                        .HasColumnType("int")
                        .HasColumnName("act4points");

                    b.Property<int>("Act4Victims")
                        .HasColumnType("int")
                        .HasColumnName("act4victims");

                    b.Property<string>("Biography")
                        .HasColumnType("longtext")
                        .HasColumnName("biography");

                    b.Property<byte>("Class")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("class");

                    b.Property<short>("Compliments")
                        .HasColumnType("smallint")
                        .HasColumnName("compliments");

                    b.Property<bool>("CursorAimLock")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("cursoraimlock");

                    b.Property<byte>("Dignity")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("dignity");

                    b.Property<long>("Exp")
                        .HasColumnType("bigint")
                        .HasColumnName("exp");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("gender");

                    b.Property<long>("Gold")
                        .HasColumnType("bigint")
                        .HasColumnName("gold");

                    b.Property<byte>("HairColor")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("haircolor");

                    b.Property<byte>("HairStyle")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("hairstyle");

                    b.Property<int>("Health")
                        .HasColumnType("int")
                        .HasColumnName("health");

                    b.Property<long>("HeroExp")
                        .HasColumnType("bigint")
                        .HasColumnName("heroexp");

                    b.Property<byte>("HeroLevel")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("herolevel");

                    b.Property<bool>("IsArenaChampion")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isarenachampion");

                    b.Property<bool>("IsBlockedBuff")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isblockedbuff");

                    b.Property<bool>("IsBlockedHat")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isblockedhat");

                    b.Property<bool>("IsBlockedHud")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isblockedhud");

                    b.Property<bool>("IsDisplayCdBlocked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isdisplaycdblocked");

                    b.Property<bool>("IsDisplayHealthBlocked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isdisplayhealthblocked");

                    b.Property<bool>("IsEmoticonBlocked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isemoticonblocked");

                    b.Property<bool>("IsExchangeBlocked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isexchangeblocked");

                    b.Property<bool>("IsFamilyRequestBlocked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isfamilyrequestblocked");

                    b.Property<bool>("IsFriendRequestBlocked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isfriendrequestblocked");

                    b.Property<bool>("IsGroupRequestBlocked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isgrouprequestblocked");

                    b.Property<bool>("IsHealthBlocked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ishealthblocked");

                    b.Property<bool>("IsHeroChatBlocked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isherochatblocked");

                    b.Property<bool>("IsMinilandInviteBlocked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isminilandinviteblocked");

                    b.Property<bool>("IsPartnerAutoRelive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ispartnerautorelive");

                    b.Property<bool>("IsPetAutoRelive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ispetautorelive");

                    b.Property<bool>("IsQuickGetUpBlocked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isquickgetupblocked");

                    b.Property<bool>("IsWhispBlocked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("iswhispblocked");

                    b.Property<long>("JobExp")
                        .HasColumnType("bigint")
                        .HasColumnName("jobexp");

                    b.Property<byte>("JobLevel")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("joblevel");

                    b.Property<byte>("Level")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("level");

                    b.Property<int>("Mana")
                        .HasColumnType("int")
                        .HasColumnName("mana");

                    b.Property<short>("MapId")
                        .HasColumnType("smallint")
                        .HasColumnName("mapid");

                    b.Property<short>("MapPosX")
                        .HasColumnType("smallint")
                        .HasColumnName("mapposx");

                    b.Property<short>("MapPosY")
                        .HasColumnType("smallint")
                        .HasColumnName("mapposy");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("int")
                        .HasColumnName("maxhealth");

                    b.Property<int>("MaxMana")
                        .HasColumnType("int")
                        .HasColumnName("maxmana");

                    b.Property<byte>("MaxPets")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("maxpets");

                    b.Property<string>("MinilandMsg")
                        .HasColumnType("longtext")
                        .HasColumnName("minilandmsg");

                    b.Property<short>("MinilandPts")
                        .HasColumnType("smallint")
                        .HasColumnName("minilandpts");

                    b.Property<bool>("MinilandState")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("minilandstate");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<long>("RagePts")
                        .HasColumnType("bigint")
                        .HasColumnName("ragepts");

                    b.Property<int>("Reputation")
                        .HasColumnType("int")
                        .HasColumnName("reputation");

                    b.Property<byte>("Slot")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("slot");

                    b.Property<int>("SpecialistAddPts")
                        .HasColumnType("int")
                        .HasColumnName("specialistaddpts");

                    b.Property<int>("SpecialistPts")
                        .HasColumnType("int")
                        .HasColumnName("specialistpts");

                    b.Property<byte>("State")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("state");

                    b.Property<int>("TalentArenaLoses")
                        .HasColumnType("int")
                        .HasColumnName("talentarenaloses");

                    b.Property<int>("TalentArenaSurrender")
                        .HasColumnType("int")
                        .HasColumnName("talentarenasurrender");

                    b.Property<int>("TalentArenaWins")
                        .HasColumnType("int")
                        .HasColumnName("talentarenawins");

                    b.HasKey("Id");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("Database.TokenDb.SessionTokens", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdat");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expiresat");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("token");

                    b.Property<string>("Username")
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("session_tokens", (string)null);
                });

            modelBuilder.Entity("Database.World.Map", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<short>("Id"));

                    b.Property<int>("Bgm")
                        .HasColumnType("int")
                        .HasColumnName("bgm");

                    b.Property<byte>("DropRate")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("droprate");

                    b.Property<byte>("ExpRate")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("exprate");

                    b.Property<byte>("GoldRate")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("goldrate");

                    b.Property<short>("Height")
                        .HasColumnType("smallint")
                        .HasColumnName("height");

                    b.Property<bool>("IsPvpAllowed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ispvpallowed");

                    b.Property<bool>("IsShopAllowed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isshopallowed");

                    b.Property<byte[]>("MapGrid")
                        .IsRequired()
                        .HasColumnType("longblob")
                        .HasColumnName("mapgrid");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<short>("Width")
                        .HasColumnType("smallint")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.ToTable("maps", (string)null);
                });

            modelBuilder.Entity("Database.Item.ItemTranslation", b =>
                {
                    b.HasOne("Database.Item.Item", "Item")
                        .WithMany("Translations")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Database.Item.Item", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
